name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: make docker-acc
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APPLICATION_KEY: ${{ secrets.DATADOG_APPLICATION_KEY }}
          STATUSPAGE_PAGE: ${{ secrets.STATUSPAGE_PAGE }}
          STATUSPAGE_TOKEN: ${{ secrets.STATUSPAGE_TOKEN }}
